### ISSUE TITLE
Adjust font sizes

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/pdf-theme#15]
We have several font sizes that are defined for official iSAQB documents. They are as follows:

### Überschriften
- 14 pt und 17 pt Zeilenabstand
- Schriftart Roboto, Schriftschnitt: bold

### Absatzheadlines
- 12 pt Schriftgröße und 15 pt Zeilenabstand
- Schriftart Roboto, Schriftschnitt: bold

### Fließtext
- 9,5 pt  Schriftgröße und 12,5 pt Zeilenabstand
- Schriftart Roboto im Schriftschnitt regular

### Aufzählungen
- 9,5 pt Schriftgröße und 12,5 pt Zeilenabstand

**Comment by gernotstarke** [comment]
did your last commits implement these definitions?

**Comment by programming-wolf** [comment]
Not completely. I’ll add the final adjustments this week.

**Comment by programming-wolf** [comment]
Everything is now as desired. However, we need to wait for asciidoctorPDF 1.5.0beta-1, because this will contain required bug fixes for a proper display of the PDF file.

**Comment by gernotstarke** [comment]
with the latest changes (June 17th 2019), level-3 headings (section "Learning goals") is set in smaller font that learning goals themselves - that looks strange: 

![image](https://user-images.githubusercontent.com/1233990/60445596-cd12ee80-9c1f-11e9-966c-733a708d08a9.png)

**Comment by programming-wolf** [comment]
Yep, already fixed in the latest version. I’ll notify you once it is complete.
