### ISSUE TITLE
Scaled Agile

### ISSUE THREAD

**Issue by mistertakai** [isaqb-org/pdf-theme#24]
Ich würde mir ein neues Lernziel zu skalierter Agilität wünschen. 

SAFE ist in der Schweiz sehr verbreitet. Nexus ist eine weitere Alternative.

Ich habe leider nicht die Zeit, jetzt alles im Detail auszuformulieren, kann das aber einplanen, wenn das Thema auf Interesse stösst. 

Vielen Dank für das Anschauen.

**Comment by sippsack** [comment]
Das ist vermutlich im falschen Repo gelandet? Ich vermute, es gehört hierzu: https://github.com/isaqb-org/curriculum-agila

**Comment by alxlo** [comment]
Wrong repo for this request.
You might want to move it to the repo of a curriculum where you want this learning goal to be considered. If you move it to https://github.com/isaqb-org/curriculum-foundation it might be considered for the next (2025) version of the foundation curriculum. Sorry it takes so long but we've just updated it and it needs to be stable for some time as there are a lot of incoming dependencies that cause a lot of people a lot of work.

However as the curriculum is already quite full, it might be wise to propose it as an R3 learning goal (=optional, not exam relevant). It might fit into LG 1-6 or under methodology trends  (R3) in LG 2-3. Please provide a _good_ link to e resource explaining this topic.

What is the learning goal? Students (should know|be able to|can apply|can name| can describe| ...) $something.
