### ISSUE TITLE
Understanding Complexity

### ISSUE THREAD

**Issue by mistertakai** [isaqb-org/pdf-theme#25]
Agilität ist die Fähigkeit zur Schöpfung in komplexen Umgebungen. Damit Architekturentscheidungen nachhaltig sein können, muss diese Komplexität verstanden werden. Die Gretchenfrage lautet: auf welchen Ebenen findet Verständnis statt? Welche Methoden und Hilfsmittel kann ich dem Architekten mitgeben, damit er zu besseren Lösungen im Kontext findet?

Das überschneidet sich mit den Inhalten von SOFT. Dennoch könnte man Themen wie Arbeitskultur aufnehmen. Auch fehlt heute eine Einordnung in die verschiedenen Formen der Selbstorganisation wie Soziokratie oder Holokratie.

**Comment by sippsack** [comment]
Das ist vermutlich im falschen Repo gelandet? Ich vermute, es gehört hierzu: https://github.com/isaqb-org/curriculum-agila

**Comment by alxlo** [comment]
Wrong repo for this issue. See #24. 

Also: Please provide some resource link and try to formulate a learning goal or learning outcome.
